//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTeacher
    {
        public int StudentTeacherID { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> TecherId { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        public virtual StudentTeacher StudentTeacher1 { get; set; }
        public virtual StudentTeacher StudentTeacher2 { get; set; }
        public virtual StudentTeacher StudentTeacher11 { get; set; }
        public virtual StudentTeacher StudentTeacher3 { get; set; }
        public virtual Student Student { get; set; }
    }
}
